
import javax.swing.ImageIcon;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author crism
 */
public class Examen1 extends javax.swing.JFrame {

    ImageIcon c = new ImageIcon("imagenes/circle.png");
    ImageIcon e = new ImageIcon("imagenes/x.png");
    int gato [][] = new int [3][3];
    int cont=0;
    int a,b;
    

    /**
     * Creates new form Examen1
     */
    public Examen1() {
        gato[0][0]=11;
        gato[0][1]=12;
        gato[0][2]=13;
        gato[1][0]=14;
        gato[1][1]=15;
        gato[1][2]=16;
        gato[2][0]=17;
        gato[2][1]=18;
        gato[2][2]=19;

        initComponents();
        jTextField1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextField1.setText("Turno Jugador 1.");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jButton1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  

      if(cont==8){
          
      jTextField1.setText("Empate");
      jButton1.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));

        }else if(cont % 2 == 0) {
            
           gato[0][0]=0;
          jTextField1.setText("Turno Jugador 2");
          jButton1.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
          cont++;
          
          if(gato[0][0]==gato[0][1]&&gato[0][1]==gato[0][2]){
          
            jTextField1.setText("Gana Jugador 1");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            
          
          }else if(gato[0][0]==gato[1][0]&&gato[1][0]==gato[2][0]){
              
            jTextField1.setText("Gana Jugador 1");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }else if(gato[0][0]==gato[1][1]&&gato[1][1]==gato[2][2]){
              
            jTextField1.setText("Gana Jugador 1"); 
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
              
          }
          
      }else{
            gato[0][0]=1;
          jTextField1.setText("Turno Jugador 1");
          jButton1.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\circle.png"));
          cont++;
          if(gato[0][0]==gato[0][1]&&gato[0][1]==gato[0][2]){
          
            jTextField1.setText("Gana Jugador 2 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[0][0]==gato[1][0]&&gato[1][0]==gato[2][0]){
              
            jTextField1.setText("Gana Jugador 2 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }else if(gato[0][0]==gato[1][1]&&gato[1][1]==gato[2][2]){
              
            jTextField1.setText("Gana Jugador 2 "); 
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
              
          }
      }
      
      jButton1.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
      if(cont==8){
          
        jTextField1.setText("Empate");
        jButton1.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
        }else if(cont % 2 == 0) {
            gato[0][1]=0;
          jTextField1.setText("Turno Jugador 2");
          jButton2.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
          cont++;
          if(gato[0][0]==gato[0][1]&&gato[0][0]==gato[0][2]){
          
            jTextField1.setText("Gana Jugador 1 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[0][1]==gato[1][1]&&gato[1][1]==gato[2][1]){
              
            jTextField1.setText("Gana Jugador 1 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }   
      }else{
            gato[0][1]=1;
          jTextField1.setText("Turno Jugador 1");
          jButton2.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\circle.png"));
          cont++;
         if(gato[0][0]==gato[0][1]&&gato[0][0]==gato[0][2]){
          
            jTextField1.setText("Gana Jugador 2 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[0][1]==gato[1][1]&&gato[1][1]==gato[2][1]){
              
            jTextField1.setText("Gana Jugador 2 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }   
      }
            jButton2.setEnabled(false);
// TODO add y    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           
      if(cont==8){
          
        jTextField1.setText("Empate");
        jButton1.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
        }else if(cont % 2 == 0) {
            gato[0][2]=0;
          jTextField1.setText("Turno Jugador 2");
          jButton3.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
          cont++;
          if(gato[0][0]==gato[0][1]&&gato[0][1]==gato[0][2]){
          
            jTextField1.setText("Gana Jugador 1");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[0][2]==gato[1][2]&&gato[1][2]==gato[2][2]){
              
            jTextField1.setText("Gana Jugador 1");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }else if(gato[0][2]==gato[1][1]&&gato[1][1]==gato[2][0]){
              
            jTextField1.setText("Gana Jugador 1"); 
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
              
          }
      }else{
            gato[0][2]=1;
          jTextField1.setText("Turno Jugador 1");
          jButton3.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\circle.png"));
          cont++;
          if(gato[0][0]==gato[0][1]&&gato[0][1]==gato[0][2]){
          
            jTextField1.setText("Gana Jugador 2");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[0][2]==gato[1][2]&&gato[1][2]==gato[2][2]){
              
            jTextField1.setText("Gana Jugador 2");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }else if(gato[0][2]==gato[1][1]&&gato[1][1]==gato[2][0]){
              
            jTextField1.setText("Gana Jugador 2"); 
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
              
          }          
      }
       jButton3.setEnabled(false);     
// TODO add y   // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
           
       if(cont==8){
          
           jTextField1.setText("Empate");
           jButton1.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
        }else if(cont % 2 == 0) {
            gato[1][2]=0;
          jTextField1.setText("Turno Jugador 2");
          jButton6.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
          cont++;
          if(gato[1][2]==gato[1][1]&&gato[1][1]==gato[1][0]){
          
            jTextField1.setText("Gana Jugador 1 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[0][2]==gato[1][2]&&gato[1][2]==gato[2][2]){
              
            jTextField1.setText("Gana Jugador 1 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }   
      }else{
            gato[1][2]=1;
          jTextField1.setText("Turno Jugador 1");
          jButton6.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\circle.png"));
          cont++;
          if(gato[1][2]==gato[1][1]&&gato[1][1]==gato[1][0]){
          
            jTextField1.setText("Gana Jugador 2 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[0][2]==gato[1][2]&&gato[1][2]==gato[2][2]){
              
            jTextField1.setText("Gana Jugador 2 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }             
      }
            jButton6.setEnabled(false);
// TODO add y   // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            
      if(cont==8){
          
         jTextField1.setText("Empate");
         jButton1.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
      }else if(cont % 2 == 0) {
          gato[1][0]=0;
          jTextField1.setText("Turno Jugador 2");
          jButton4.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
          cont++;
         if(gato[1][2]==gato[1][1]&&gato[1][1]==gato[1][0]){
          
            jTextField1.setText("Gana Jugador 1 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[0][0]==gato[1][0]&&gato[1][0]==gato[2][0]){
              
            jTextField1.setText("Gana Jugador 1 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }   
      }else{
          gato[1][0]=1;
          jTextField1.setText("Turno Jugador 1");
          jButton4.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\circle.png"));
          cont++;
         if(gato[1][2]==gato[1][1]&&gato[1][1]==gato[1][0]){
          
            jTextField1.setText("Gana Jugador 2 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[0][0]==gato[1][0]&&gato[1][0]==gato[2][0]){
              
            jTextField1.setText("Gana Jugador 2 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }           
      }
            jButton4.setEnabled(false);
// TODO add y  // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
           
       if(cont==8){
          
            jTextField1.setText("Empate");
            jButton1.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
        }else if(cont % 2 == 0) {
            gato[1][1]=0;
          jTextField1.setText("Turno Jugador 2");
          jButton5.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
          cont++;
          if(gato[1][1]==gato[1][0]&&gato[1][0]==gato[1][2]){
          
            jTextField1.setText("Gana Jugador 1");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[1][1]==gato[0][1]&&gato[1][1]==gato[2][1]){
              
            jTextField1.setText("Gana Jugador 1");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }else if(gato[0][0]==gato[1][1]&&gato[1][1]==gato[2][2]){
              
            jTextField1.setText("Gana Jugador 1"); 
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
              
          }else if(gato[0][2]==gato[1][1]&&gato[1][1]==gato[2][0]){
              
              jTextField1.setText("Gana Jugador 1"); 
              jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          }          
      }else{
           gato[1][1]=1;
          jTextField1.setText("Turno Jugador 1");
          jButton5.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\circle.png"));
          cont++;
          if(gato[1][1]==gato[1][0]&&gato[1][0]==gato[1][2]){
          
            jTextField1.setText("Gana Jugador 2");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[1][1]==gato[0][1]&&gato[1][1]==gato[2][1]){
              
            jTextField1.setText("Gana Jugador 2");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }else if(gato[0][0]==gato[1][1]&&gato[1][1]==gato[2][2]){
              
            jTextField1.setText("Gana Jugador 2"); 
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
              
          }else if(gato[0][2]==gato[1][1]&&gato[1][1]==gato[2][0]){
              
              jTextField1.setText("Gana Jugador 2"); 
              jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          }         
      }
            jButton5.setEnabled(false);
// TODO add y   // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
           
        
       if(cont==8){
          
            jTextField1.setText("Empate");
            jButton1.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
        }else if(cont % 2 == 0) {
            gato[2][0]=0;
          jTextField1.setText("Turno Jugador 2");
          jButton7.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
          cont++;
          if(gato[2][0]==gato[2][1]&&gato[2][1]==gato[2][2]){
          
            jTextField1.setText("Gana Jugador 1");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[2][0]==gato[1][0]&&gato[1][0]==gato[0][0]){
              
            jTextField1.setText("Gana Jugador 1");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }else if(gato[2][0]==gato[1][1]&&gato[1][1]==gato[0][2]){
              
            jTextField1.setText("Gana Jugador 1"); 
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
              
          }
      }else{
            gato[2][0]=1;
          jTextField1.setText("Turno Jugador 1");
          jButton7.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\circle.png"));
          cont++;
          if(gato[2][0]==gato[2][1]&&gato[2][1]==gato[2][2]){
          
            jTextField1.setText("Gana Jugador 2");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[2][0]==gato[1][0]&&gato[1][0]==gato[0][0]){
              
            jTextField1.setText("Gana Jugador 2");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }else if(gato[2][0]==gato[1][1]&&gato[1][1]==gato[0][2]){
              
            jTextField1.setText("Gana Jugador 2"); 
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
              
          }          
      }
            jButton7.setEnabled(false);
// TODO add y   // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
             
       if(cont==8){
          
           jTextField1.setText("Empate");
           jButton1.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
        }else if(cont % 2 == 0) {
            gato[2][1]=0;
          jTextField1.setText("Turno Jugador 2");
          jButton8.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
          cont++;
         if(gato[2][0]==gato[2][1]&&gato[2][1]==gato[2][2]){
          
            jTextField1.setText("Gana Jugador 1 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[2][1]==gato[1][1]&&gato[1][1]==gato[0][1]){
              
            jTextField1.setText("Gana Jugador 1 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }             
      }else{
            gato[2][1]=1;
          jTextField1.setText("Turno Jugador 1");
          jButton8.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\circle.png"));
          cont++;
          if(gato[2][0]==gato[2][1]&&gato[2][1]==gato[2][2]){
          
            jTextField1.setText("Gana Jugador 2 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[2][1]==gato[1][1]&&gato[1][1]==gato[0][1]){
              
            jTextField1.setText("Gana Jugador 2 ");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }   
      }
            jButton8.setEnabled(false);
// TODO add y // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
                        
      if(cont==8){
          
             jTextField1.setText("Empate");

        }else if(cont % 2 == 0) {
            gato[2][2]=0;
          jTextField1.setText("Turno Jugador 2");
          jButton9.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\x.png"));
          cont++;
          if(gato[2][2]==gato[2][1]&&gato[2][1]==gato[2][0]){
          
            jTextField1.setText("Gana Jugador 1");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[2][2]==gato[1][2]&&gato[1][2]==gato[0][2]){
              
            jTextField1.setText("Gana Jugador 1");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }else if(gato[2][2]==gato[1][1]&&gato[1][1]==gato[0][0]){
              
            jTextField1.setText("Gana Jugador 1"); 
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
              
          }             
      }else{
            gato[2][2]=1;
          jTextField1.setText("Turno Jugador 1");
          jButton9.setIcon(new ImageIcon("C:\\Users\\crism\\OneDrive\\Documentos\\NetBeansProjects\\CursoLenguajes3\\src\\Imagenes\\circle.png"));
          cont++;
          if(gato[2][2]==gato[2][1]&&gato[2][1]==gato[2][0]){
          
            jTextField1.setText("Gana Jugador 2");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
          
          }else if(gato[2][2]==gato[1][2]&&gato[1][2]==gato[0][2]){
              
            jTextField1.setText("Gana Jugador 2");
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);

          }else if(gato[2][2]==gato[1][1]&&gato[1][1]==gato[0][0]){
              
            jTextField1.setText("Gana Jugador 2"); 
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
              
          }            
      }
            jButton9.setEnabled(false);
// TODO add y  // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
